name: build docker image

on:
  push:
    branches: [ feature ]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Cloning code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      
      - name: Extract meta data
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ayoubgholami/rengine

      - name: build docker image
        uses: docker/build-push-action@v5
        with:
          context: web/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}